WebTraSua_197/WebTraSua_197/Models/EF/DanhMuc.cs
namespace WebTraSua_197.Models.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("DanhMuc")]
    public partial class DanhMuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhMuc()
        {
            SanPhams = new HashSet<SanPham>();
        }

        [Key]
        public long MaDanhMuc { get; set; }

        [StringLength(250)]
        public string TenDanhMuc { get; set; }

        [StringLength(50)]
        public string MetaTitle { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}

WebTraSua_197/WebTraSua_197/Models/EF/PhanHoi.cs
namespace WebTraSua_197.Models.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("PhanHoi")]
    public partial class PhanHoi
    {
        [Key]
        public int MaPhanHoi { get; set; }

        [StringLength(250)]
        public string TenNguoiPhanHoi { get; set; }

        [StringLength(500)]
        public string NoiDung { get; set; }

        public DateTime? NgayPhanHoi { get; set; }
    }
}

WebTraSua_197/WebTraSua_197/Areas/Admin/Controllers/DanhMucsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebTraSua_197.Models.EF;

namespace WebTraSua_197.Areas.Admin.Controllers
{
    public class DanhMucsController : Controller
    {
        private WebTraSua db = new WebTraSua();

        // GET: Admin/DanhMucs
        public ActionResult Index()
        {
            return View(db.DanhMucs.ToList());
        }

        // GET: Admin/DanhMucs/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            if (danhMuc == null)
            {
                return HttpNotFound();
            }
            return View(danhMuc);
        }

        // GET: Admin/DanhMucs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/DanhMucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDanhMuc,TenDanhMuc,MetaTitle")] DanhMuc danhMuc)
        {
            if (ModelState.IsValid)
            {
                db.DanhMucs.Add(danhMuc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(danhMuc);
        }

        // GET: Admin/DanhMucs/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            if (danhMuc == null)
            {
                return HttpNotFound();
            }
            return View(danhMuc);
        }

        // POST: Admin/DanhMucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDanhMuc,TenDanhMuc,MetaTitle")] DanhMuc danhMuc)
        {
            if (ModelState.IsValid)
            {
                db.Entry(danhMuc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(danhMuc);
        }

        // GET: Admin/DanhMucs/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            if (danhMuc == null)
            {
                return HttpNotFound();
            }
            return View(danhMuc);
        }

        // POST: Admin/DanhMucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            db.DanhMucs.Remove(danhMuc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebTraSua_197/WebTraSua_197/Areas/Admin/Controllers/PhanHoisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebTraSua_197.Models.EF;

namespace WebTraSua_197.Areas.Admin.Controllers
{
    public class PhanHoisController : Controller
    {
        private WebTraSua db = new WebTraSua();

        // GET: Admin/PhanHois
        public ActionResult Index()
        {
            return View(db.PhanHois.ToList());
        }

        // GET: Admin/PhanHois/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhanHoi phanHoi = db.PhanHois.Find(id);
            if (phanHoi == null)
            {
                return HttpNotFound();
            }
            return View(phanHoi);
        }

        // GET: Admin/PhanHois/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/PhanHois/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaPhanHoi,TenNguoiPhanHoi,NoiDung,NgayPhanHoi")] PhanHoi phanHoi)
        {
            if (ModelState.IsValid)
            {
                db.PhanHois.Add(phanHoi);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(phanHoi);
        }

        // GET: Admin/PhanHois/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhanHoi phanHoi = db.PhanHois.Find(id);
            if (phanHoi == null)
            {
                return HttpNotFound();
            }
            return View(phanHoi);
        }

        // POST: Admin/PhanHois/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaPhanHoi,TenNguoiPhanHoi,NoiDung,NgayPhanHoi")] PhanHoi phanHoi)
        {
            if (ModelState.IsValid)
            {
                db.Entry(phanHoi).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(phanHoi);
        }

        // GET: Admin/PhanHois/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhanHoi phanHoi = db.PhanHois.Find(id);
            if (phanHoi == null)
            {
                return HttpNotFound();
            }
            return View(phanHoi);
        }

        // POST: Admin/PhanHois/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PhanHoi phanHoi = db.PhanHois.Find(id);
            db.PhanHois.Remove(phanHoi);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebTraSua_197/WebTraSua_197/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebTraSua_197.Models.Fun;

namespace WebTraSua_197.Controllers
{
    public class SanPhamController : Controller
    {
        // GET: SanPham
        public ActionResult SanPham(long MaDanhMuc)
        {
            var danhmuc = new DanhMucF().DanhMucSP(MaDanhMuc);
            ViewBag.SanPham = new DanhMucF().ListAllSP(danhmuc.MaDanhMuc);
            return View(MaDanhMuc);
        }
        public ActionResult AllSanPham(int page = 1, int pageSize = 3)
        {
            var model = new SanPhamF().ListAllPaging(page, pageSize);
            ViewBag.ListAllSP = new SanPhamF().ListAllSP();
            return View(model);
        }
        [ChildActionOnly]
        public PartialViewResult DanhMuc()
        {
            var model = new DanhMucF().ListAll();
            return PartialView(model);
        }
        public ActionResult ListSanPham()
        {
            var model = new SanPhamF().ListSP(3);
            return PartialView(model);
        }
        public PartialViewResult ListSanPhamLQ()
        {
            var model = new SanPhamF().ListSP(3);
            return PartialView(model);
        }
        public ActionResult ChiTietSanPham(long MaSanPham)
        {
            var spOD = new SanPhamF().Detail(MaSanPham);
            ViewBag.Detail = new SanPhamF().Detail(spOD.MaSanPham);
            ViewBag.ListDetail = new SanPhamF().ListDetail(spOD.MaSanPham);
            ViewBag.Topping = new SanPhamF().Topping();
            ViewBag.Duong = new SanPhamF().Duong();
            ViewBag.Da = new SanPhamF().Da();
            return View(spOD);
        }
    }
}

WebTraSua_197/WebTraSua_197/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebTraSua_197.Common;
using WebTraSua_197.Models.EF;
using WebTraSua_197.Models.Fun;
using WebTraSua_197.Models.User;


namespace WebTraSua_197.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new UserF();
                var result = dao.Login(model.UserName, model.Pass);
                if (result)
                {
                    var user = dao.GetById(model.UserName);
                    var userSession = new UserLogin();
                    /// userSession.UserName = user.UserName;
                    userSession.UserName = "admin";
                    userSession.MaNguoiDung = user.MaNguoiDung;

                    Session.Add(CommonConstants.USER_SESSION, userSession);
                    // return RedirectToAction("Index", "Home");
                    return Redirect("/Admin");
                }
                else
                {
                    ModelState.AddModelError("", "Đăng nhập không thành công.");
                }
            }
            return View("Login");
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new UserF();
                if (dao.CheckUserName(model.UserName))
                {
                    ModelState.AddModelError("", "Tên đăng nhập đã tồn tại");
                }
                else if (dao.CheckSDT(model.SDT))
                {
                    ModelState.AddModelError("", "Số điện thoại đã tồn tại");
                }
                else
                {
                    var user = new NguoiDung();
                    user.TenNguoiDung = model.TenNguoiDung;
                    user.UserName = model.UserName;
                    user.Pass = model.Pass;
                    user.DiaChi = model.DiaChi;
                    user.SDT = model.SDT;
                    var result = dao.Insert(user);
                    if (result > 0)
                    {
                        ViewBag.Success = "Đăng ký thành công";
                        model = new RegisterModel();
                    }
                    else
                    {
                        ModelState.AddModelError("", "Đăng ký không thành công");
                    }
                }
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult PhanHoi()
        {
            return View();
        }
        [HttpPost]
        public ActionResult PhanHoi(PhanHoiModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new PhanHoiF();
                var ph = new PhanHoi();
                ph.TenNguoiPhanHoi = model.TenNguoiDung;

                ph.NoiDung = model.NoiDung;
                ph.NgayPhanHoi = DateTime.Now;

                var result = dao.InsertPH(ph);
                if (result > 0)
                {
                    ViewBag.Success = "Gửi phản hồi thành công";
                    model = new PhanHoiModel();
                }
                else
                {
                    ModelState.AddModelError("", "Gửi phản hồi không thành công");
                }
            }
            return View(model);
        }
         public ActionResult TaiKhoan()
        {
            var model = new UserF().GHUser();
            return View(model);
        }
        public ActionResult Logout()
        {
            Session[CommonConstants.USER_SESSION] = null;

            return RedirectToAction("Index", "Home");
        }
    }
}

WebTraSua_197/WebTraSua_197/Views/Shared/DanhMuc.cshtml
@model List<WebTraSua_197.Models.EF.DanhMuc>
<div class="h_menu4">
    <!-- start h_menu4 -->
    <a class="toggleMenu" href="#">Menu</a>
    <ul class="nav">
        @foreach (var it in Model)
        {
            <li><a href="/danh-muc/@it.MetaTitle-@it.MaDanhMuc">@it.TenDanhMuc</a></li>
        }

    </ul>
    <script type="text/javascript" src="/Content/js/nav.js"></script>
</div><!-- end h_menu4 -->

WebTraSua_197/WebTraSua_197/Views/Shared/PhanHoi.cshtml
@model List<WebTraSua_197.Models.EF.PhanHoi>
@foreach (var it in Model)
{
    <div class="news">

        <p>@it.NoiDung </p>
        <div class="foot">
            <label>@it.TenNguoiPhanHoi</label>
            <ul class="eye ">
              
            </ul>
            <div class="clearfix"> </div>
        </div>
    </div>
}

WebTraSua_197/WebTraSua_197/Views/Shared/_Layout.cshtml
@using WebTraSua_197.Common
<!DOCTYPE html>
<html>
<head>
    <title>Trà sữa 21</title>
    <link href="/Content/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="/Content/js/jquery.min.js"></script>
    <!-- Custom Theme files -->
    <!--theme-style-->
    <link href="/Content/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!--//theme-style-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Sport Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--fonts-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
    <!--//fonts-->
    <style>
        .textcl {
            color: white;
        }
    </style>
</head>
<body>
    <!--header-->
    <div class="line">

    </div>
    <div class="header">
        <div class="logo">
            <a href="/Home/Index"><img src="/Content/images/logo.png" alt=""></a>
        </div>
        <div class="header-top">
            <div class="header-grid">

                @{
                    var session = (UserLogin)Session[WebTraSua_197.Common.CommonConstants.USER_SESSION];
                }
                @if (session == null)
                {
                    <ul class="header-in">
                        <li><a href="/User/Login">Đăng nhập   </a> </li>
                        <li><a href="/User/Register">Đăng ký   </a> </li>
                    </ul>
                }
                else
                {
                    var link = "/tai-khoan/";
                    <ul class="header-in">
                        <li><a href="@link">Tài khoản</a> </li>
                        <li>@Html.ActionLink("Đăng xuất", "Logout", "User")</li>
                    </ul>

                }

                <div class="search-box">
                    <div id="sb-search" class="sb-search">
                        <form method="post" action="/Home/TimKiem">
                            <input class="sb-search-input" placeholder="Nhập thông tin cần tìm..." type="search" name="search" id="search">
                            <input class="sb-search-submit" type="submit" value="">
                            <span class="sb-icon-search"> </span>
                        </form>
                    </div>
                </div>
                <!-- search-scripts -->
                <script src="/Content/js/classie.js"></script>
                <script src="/Content/js/uisearch.js"></script>
                <script>
                    new UISearch(document.getElementById('sb-search'));
                </script>
                <!-- //search-scripts -->
                <div class="online">
                    <a href="/Cart/Index">Giỏ hàng</a>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="header-bottom">
                @{Html.RenderAction("DanhMuc", "SanPham");}
                <ul class="header-bottom-in">
                    <li class="textcl">
                        Liên hệ: (+84)869668106

                    </li>

                </ul>
                <div class="clearfix"> </div>
            </div>
        </div>
        <div class="clearfix"> </div>
    </div>
    <!---->

    @RenderBody()
    <!---->
    <!--footer-->
    <div class="footer">
        <div class="col-md-3 footer-left left-footer">
            <h4>Cửa hàng</h4>
            <div class="run-top top-run">
                <ul class="run-grid">
                    <li><a href="#">(+84) 869668106</a></li>
                    <li><a href="#">236 Hoàng Quốc Việt, Từ Liêm, Hà Nội</a></li>
                </ul>
                <div class="clearfix"> </div>
            </div>
        </div>
        <div class="col-md-3 footer-left left-footer">
            <h4>Đóng góp ý kiến</h4>
            <div class="run-top top-run">
                <ul class="run-grid">
                    <li><a href="contact.html">Viết phản hồi</a></li>
                    <li><a href="#">Gọi điện</a></li>
                    <li><a href="">(+84)869668106</a></li>
                </ul>

                <div class="clearfix"> </div>
            </div>
        </div>
        <div class="col-md-2 footer-left left-footer">
            <h4>Tài khoản</h4>
            <ul class="run-grid-in">
                <li><a href="account.html">Đăng nhập</a></li>
                <li><a href="register.html">Đăng ký</a></li>

            </ul>
        </div>
        <div class="col-md-4 footer-left left-footer">
            <h4>Mạng xã hội</h4>
            <div class="letter">
                <ul class="social-in">
                    <li><a href="#"><i> </i></a></li>
                    <li><a href="#"><i class="youtube"> </i></a></li>
                    <li><a href="#"><i class="facebook"> </i></a></li>
                    <li><a href="#"><i class="twitter"> </i></a></li>
                </ul>


                <h6>Hãy theo dõi chúng tôi!</h6>

                <p class="footer-class"> © 2020 Sport Shop |  <a href="" target="_blank">Ha Noi, Viet Nam</a> </p>
            </div>

        </div>
        <div class="clearfix"> </div>
    </div>
    @RenderSection("jsFooter", required: false)
</body>
</html>